### ISSUE TITLE
Add well-known nodeSelector to operator deployment

### ISSUE THREAD

**Issue by kzombro-pfl** [apache/incubator-kie-kogito-operator#1523]
### Description

Hello !
I have a hybrid kubernetes cluster comprised of windows and linux workers. Without a proper nodeSelector for operating system, the operator sometimes schedules onto a windows node and fails out. My suggestion is to include a well-known nodeSelector on the operator deployment such that it properly targets compatible linux workers.

### Implementation ideas

in the `.spec.template.spec` of the operator deployment, add in 
```
+      nodeSelector:
+        kubernetes.io/os: linux
```

**Comment by ricardozanini** [comment]
This project has been closed, please see #1537
